parameters:
#    acme_guest_book.example.class: Acme\GuestBookBundle\Example

services:
#    acme_guest_book.example:
#        class: %acme_guest_book.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
